default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^templates/templated_email/compiled/
        exclude_types: [ svg ]
      - id: end-of-file-fixer
        exclude: ^templates/templated_email/compiled/
        exclude_types: [ svg ]
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: detect-private-key # detects the presence of private keys.
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      - id: mixed-line-ending # replaces or checks mixed line ending.

  #      - repo: https://github.com/astral-sh/ruff-pre-commit
  #        rev: v0.6.5
  #        hooks:
  #          - id: ruff
  #          - id: ruff-format
  #            args: [ '--diff' ]


  #      - repo: https://github.com/pre-commit/mirrors-autopep8
  #        rev: "v2.0.4"
  #        hooks:
  #          - id: autopep8
  #            args: [ '--diff' ]

  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.0"
    hooks:
      - id: poetry-export
        args:
          [
            "-f",
            "requirements.txt",
            "-o",
            "requirements.txt",
            "--without-hashes",
          ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
